### ISSUE TITLE
setup file syntax correction

### ISSUE THREAD

**Issue by johri-lab** [NJACKWinterOfCode/B.E.N.J.I.#9]
Errors in the setup file making it impossible to install the dependencies.

**Comment by dhruvapte26** [comment]
Could you please elaborate on this @johri002 ?

**Comment by johri-lab** [comment]
> Could you please elaborate on this @johri002 ?

There were some basic syntax errors in the setup file that needed correction in order to install the dependencies.

**Comment by dhruvapte26** [comment]
Issue resolved. Closing issue
